export const APP_PERMISSIONS = {
  APPS_VIEW: "apps:view",
  APPS_UPDATE: "apps:update",
  APP_MEMBERS_VIEW: "apps:members:view",
  APP_MEMBERS_UPDATE: "apps:members:update",
  APP_ROLES_VIEW: "apps:roles:view",
  APP_ROLES_UPDATE: "apps:roles:update",
  APP_DEPARTMENTS_VIEW: "apps:departments:view",
  APP_DEPARTMENTS_UPDATE: "apps:departments:update",
  APP_POSITIONS_VIEW: "apps:positions:view",
  APP_POSITIONS_UPDATE: "apps:positions:update",
  KNOWLEDGE_BASE_VIEW: "knowledge-base:view",
  KNOWLEDGE_BASE_CREATE: "knowledge-base:create",
  KNOWLEDGE_BASE_UPDATE: "knowledge-base:update",
  KNOWLEDGE_BASE_DELETE: "knowledge-base:delete",
  DATA_SOURCES_VIEW: "system:datasource:view",
  DATA_SOURCES_CREATE: "system:datasource:create",
  DATA_SOURCES_UPDATE: "system:datasource:update",
  DATA_SOURCES_DELETE: "system:datasource:delete",
  DATA_SOURCES_QUERY: "system:datasource:query",
  DATA_SOURCES_SCHEMA_WRITE: "system:datasource:schema-write",
  APP_ADMIN: "app:admin",
  APP_USER: "app:user",
  USERS_VIEW: "users:view",
} as const;
