export interface DatabaseCenterLabels {
  title: string;
  subtitle: string;
  refresh: string;
  newDatabase: string;
  hostProfiles: string;
  sources: string;
  searchSources: string;
  schemas: string;
  noSource: string;
  noSchema: string;
  loading: string;
  loadFailed: string;
  details: string;
  structure: string;
  erDiagram: string;
  sqlEditor: string;
  dock: string;
  tables: string;
  views: string;
  procedures: string;
  triggers: string;
  columns: string;
  preview: string;
  ddl: string;
  copy: string;
  execute: string;
  format: string;
  limit: string;
  affectedRows: string;
  elapsedMs: string;
  createHostProfile: string;
  editHostProfile: string;
  testConnection: string;
  save: string;
  cancel: string;
  delete: string;
  name: string;
  driver: string;
  description: string;
  connectionString: string;
  sqliteRootPath: string;
  defaultDatabase: string;
  defaultSchema: string;
  active: string;
  defaultProfile: string;
  provisionMode: string;
  hostProfile: string;
  physicalDatabase: string;
  environmentMode: string;
  next: string;
  previous: string;
  create: string;
  basicInfo: string;
  hosting: string;
  confirm: string;
  wizardBasicHint: string;
  wizardHostingHint: string;
  createSuccess: string;
  saveSuccess: string;
  testSuccess: string;
  emptyStructure: string;
  readOnly: string;
  createTableVisual: string;
  createTableSql: string;
  createView: string;
  tableName: string;
  viewName: string;
  columnName: string;
  dataType: string;
  nullable: string;
  primaryKey: string;
  autoIncrement: string;
  defaultValue: string;
  comment: string;
  addColumn: string;
  removeColumn: string;
  previewSql: string;
  sqlCreateTable: string;
  viewSelectSql: string;
  previewSuccess: string;
  overview: string;
  dataSourceManagement: string;
  aiDatabases: string;
  backupManagement: string;
  auditLogs: string;
  settingsCenter: string;
  globalActions: string;
  importDdl: string;
  connected: string;
  disconnected: string;
  allDrivers: string;
  allStatuses: string;
  allEnvironments: string;
  updatedAt: string;
  actions: string;
  editStructure: string;
  queryData: string;
  viewDdl: string;
  openSqlWindow: string;
  deleteObject: string;
  functions: string;
  events: string;
  tableList: string;
  viewList: string;
  dataPreview: string;
  storedProcedures: string;
  searchSchemas: string;
  searchTablesFields: string;
  autoLayout: string;
  fitCanvas: string;
  zoomIn: string;
  zoomOut: string;
  connectionInfo: string;
  configInfo: string;
  performanceMonitor: string;
  recentLogs: string;
  objectStats: string;
  close: string;
  download: string;
  noObjectSelected: string;
  deleteConfirmTitle: string;
  deleteConfirmContent: string;
  dangerConfirm: string;
  dragTemplateHint: string;
  fieldTemplates: string;
  moveUp: string;
  moveDown: string;
  guideSourcesHint: string;
  guideSchemasHint: string;
  guideStructureHint: string;
  guideDetailsHint: string;
  guideGlobalActionsHint: string;
  importDdlHint: string;
}

export const defaultDatabaseCenterLabels: DatabaseCenterLabels = {
  title: "数据库管理中心",
  subtitle: "管理 AI 数据库、托管配置、Schema 结构与 SQL 查询。",
  refresh: "刷新",
  newDatabase: "新建数据库",
  hostProfiles: "托管配置",
  sources: "数据源",
  searchSources: "搜索数据库",
  schemas: "Schema",
  noSource: "请选择一个数据库资源",
  noSchema: "暂无 Schema",
  loading: "加载中",
  loadFailed: "加载失败",
  details: "详情",
  structure: "结构",
  erDiagram: "ER 图",
  sqlEditor: "SQL 编辑器",
  dock: "Dock",
  tables: "表",
  views: "视图",
  procedures: "存储过程",
  triggers: "触发器",
  columns: "字段",
  preview: "预览",
  ddl: "DDL",
  copy: "复制",
  execute: "执行",
  format: "格式化",
  limit: "行数",
  affectedRows: "影响行数",
  elapsedMs: "耗时",
  createHostProfile: "新建托管配置",
  editHostProfile: "编辑托管配置",
  testConnection: "测试连接",
  save: "保存",
  cancel: "取消",
  delete: "删除",
  name: "名称",
  driver: "驱动",
  description: "描述",
  connectionString: "连接串",
  sqliteRootPath: "SQLite 根目录",
  defaultDatabase: "默认库名",
  defaultSchema: "默认 Schema",
  active: "启用",
  defaultProfile: "默认配置",
  provisionMode: "开通模式",
  hostProfile: "托管配置",
  physicalDatabase: "物理库名",
  environmentMode: "环境模式",
  next: "下一步",
  previous: "上一步",
  create: "创建",
  basicInfo: "基础信息",
  hosting: "托管",
  confirm: "确认",
  wizardBasicHint: "填写资源名称和驱动类型。",
  wizardHostingHint: "选择托管配置和物理库策略。",
  createSuccess: "创建成功",
  saveSuccess: "保存成功",
  testSuccess: "连接测试通过",
  emptyStructure: "当前 Schema 暂无结构对象",
  readOnly: "只读",
  createTableVisual: "可视化建表",
  createTableSql: "SQL 建表",
  createView: "新建视图",
  tableName: "表名",
  viewName: "视图名",
  columnName: "字段名",
  dataType: "数据类型",
  nullable: "可空",
  primaryKey: "主键",
  autoIncrement: "自增",
  defaultValue: "默认值",
  comment: "注释",
  addColumn: "添加字段",
  removeColumn: "移除字段",
  previewSql: "预览 SQL",
  sqlCreateTable: "SQL 建表语句",
  viewSelectSql: "视图 SELECT",
  previewSuccess: "预览成功",
  overview: "概览",
  dataSourceManagement: "数据源管理",
  aiDatabases: "AI 数据库",
  backupManagement: "备份管理",
  auditLogs: "审计日志",
  settingsCenter: "设置中心",
  globalActions: "全局操作",
  importDdl: "导入 DDL",
  connected: "已连接",
  disconnected: "连接失败",
  allDrivers: "全部类型",
  allStatuses: "全部状态",
  allEnvironments: "全部环境",
  updatedAt: "更新时间",
  actions: "操作",
  editStructure: "编辑结构",
  queryData: "查询数据",
  viewDdl: "查看 DDL",
  openSqlWindow: "打开 SQL 窗口",
  deleteObject: "删除对象",
  functions: "函数",
  events: "事件",
  tableList: "表列表",
  viewList: "视图",
  dataPreview: "数据预览",
  storedProcedures: "存储过程",
  searchSchemas: "搜索 Schema / 对象",
  searchTablesFields: "搜索表或字段",
  autoLayout: "自动布局",
  fitCanvas: "适应画布",
  zoomIn: "放大",
  zoomOut: "缩小",
  connectionInfo: "连接信息",
  configInfo: "配置信息",
  performanceMonitor: "性能监控",
  recentLogs: "最近连接日志",
  objectStats: "对象统计",
  close: "关闭",
  download: "下载",
  noObjectSelected: "请选择表或视图",
  deleteConfirmTitle: "危险删除确认",
  deleteConfirmContent: "删除后不可恢复，请输入对象名称并勾选确认。",
  dangerConfirm: "我确认删除该对象",
  dragTemplateHint: "可从字段模板拖入字段，字段行支持上下移动排序，数据类型可拖放到类型单元格。",
  fieldTemplates: "字段模板",
  moveUp: "上移",
  moveDown: "下移",
  guideSourcesHint: "展示所有类型的数据源及连接状态，支持快速筛选与管理",
  guideSchemasHint: "按实例展示 Schema、表、视图、函数、触发器和事件",
  guideStructureHint: "一体化维护 ER 图、表结构、SQL、数据预览与 DDL",
  guideDetailsHint: "展示当前实例配置、连接状态和快捷操作",
  guideGlobalActionsHint: "提供刷新、导入 DDL、新建数据库等统一入口",
  importDdlHint: "当前导入 DDL 支持 Draft 环境下单条 CREATE TABLE 语句；多语句迁移请使用迁移任务能力。"
};
