/**
 * 与 REST API `MicroflowApiError.code` 对齐的冻结错误码。
 * 见 `docs/microflow/contracts/api-error-code-contract.md`。
 */
export type MicroflowApiErrorCode =
  | "MICROFLOW_NOT_FOUND"
  | "MICROFLOW_NAME_DUPLICATED"
  | "MICROFLOW_SCHEMA_INVALID"
  | "MICROFLOW_VALIDATION_FAILED"
  | "MICROFLOW_VERSION_CONFLICT"
  | "MICROFLOW_PUBLISH_BLOCKED"
  | "MICROFLOW_REFERENCE_BLOCKED"
  | "MICROFLOW_PERMISSION_DENIED"
  | "MICROFLOW_UNAUTHORIZED"
  | "MICROFLOW_ARCHIVED"
  | "MICROFLOW_RUN_FAILED"
  | "MICROFLOW_RUN_CANCELLED"
  | "MICROFLOW_METADATA_NOT_FOUND"
  | "MICROFLOW_METADATA_LOAD_FAILED"
  | "MICROFLOW_STORAGE_ERROR"
  | "MICROFLOW_NETWORK_ERROR"
  | "MICROFLOW_TIMEOUT"
  | "MICROFLOW_SERVICE_UNAVAILABLE"
  | "MICROFLOW_UNKNOWN_ERROR";

export const ALL_MICROFLOW_API_ERROR_CODES: readonly MicroflowApiErrorCode[] = [
  "MICROFLOW_NOT_FOUND",
  "MICROFLOW_NAME_DUPLICATED",
  "MICROFLOW_SCHEMA_INVALID",
  "MICROFLOW_VALIDATION_FAILED",
  "MICROFLOW_VERSION_CONFLICT",
  "MICROFLOW_PUBLISH_BLOCKED",
  "MICROFLOW_REFERENCE_BLOCKED",
  "MICROFLOW_PERMISSION_DENIED",
  "MICROFLOW_UNAUTHORIZED",
  "MICROFLOW_ARCHIVED",
  "MICROFLOW_RUN_FAILED",
  "MICROFLOW_RUN_CANCELLED",
  "MICROFLOW_METADATA_NOT_FOUND",
  "MICROFLOW_METADATA_LOAD_FAILED",
  "MICROFLOW_STORAGE_ERROR",
  "MICROFLOW_NETWORK_ERROR",
  "MICROFLOW_TIMEOUT",
  "MICROFLOW_SERVICE_UNAVAILABLE",
  "MICROFLOW_UNKNOWN_ERROR"
] as const;
