import { computed, onMounted, onUnmounted, reactive, ref, watch } from "vue";
import { useI18n } from "vue-i18n";
import { useRouter } from "vue-router";
import { message } from "ant-design-vue";
import type { Rule } from "ant-design-vue/es/form";
import { useAppContext } from "@/composables/useAppContext";
import {
  archiveDynamicTable,
  createDynamicTable,
  deleteDynamicTable,
  getAppScopedDynamicTables,
  getDynamicTableDeleteCheck,
  getDynamicTableSummary,
  restoreDynamicTable
} from "@/services/api-dynamic-tables";
import type {
  AppScopedDynamicTableListItem,
  DeleteCheckBlocker,
  DynamicFieldDefinition,
  DynamicTableSummary
} from "@/types/dynamic-tables";

export function useDynamicTablesWorkbench() {
  const { t } = useI18n();
  const router = useRouter();
  const { appKey, appId } = useAppContext();

  const isMounted = ref(true);
  onUnmounted(() => {
    isMounted.value = false;
  });

  const tableLoading = ref(false);
  const detailLoading = ref(false);
  const sidebarKeyword = ref("");
  const selectedTableKey = ref("");
  const tableDirectory = ref<AppScopedDynamicTableListItem[]>([]);
  const selectedTableDetail = ref<DynamicTableSummary | null>(null);
  let refreshRequestId = 0;
  const blockerModalOpen = ref(false);
  const blockerRows = ref<DeleteCheckBlocker[]>([]);
  const deleteWarnings = ref<string[]>([]);

  const statusLabel = (status: string): string => {
    const map: Record<string, string> = {
      Draft: t("dynamicTable.statusDraft"),
      Active: t("dynamicTable.statusActive"),
      HasUnpublishedChanges: t("dynamicTable.statusHasUnpublishedChanges"),
      Archived: t("dynamicTable.statusArchived"),
      Disabled: t("dynamicTable.statusDisabled")
    };
    return map[status] ?? status;
  };

  const statusTagColor = (status: string): string => {
    const map: Record<string, string> = {
      Draft: "orange",
      Active: "green",
      HasUnpublishedChanges: "gold",
      Archived: "default",
      Disabled: "red"
    };
    return map[status] ?? "default";
  };

  const filteredTables = computed(() => {
    const kw = sidebarKeyword.value.trim().toLowerCase();
    if (!kw) return tableDirectory.value;
    return tableDirectory.value.filter(
      (tbl) =>
        tbl.tableKey.toLowerCase().includes(kw) ||
        (tbl.displayName ?? "").toLowerCase().includes(kw)
    );
  });

  const fieldColumns = computed(() => [
    { title: t("dynamicTable.fieldName"), dataIndex: "name", key: "name" },
    { title: t("dynamicTable.fieldDisplayName"), dataIndex: "displayName", key: "displayName" },
    { title: t("dynamicTable.fieldType"), dataIndex: "fieldType", key: "fieldType" },
    { title: t("dynamicTable.allowNull"), dataIndex: "allowNull", key: "allowNull", width: 100 }
  ]);

  const blockerColumns = computed(() => [
    { title: t("dynamicTable.blockerType"), dataIndex: "type", key: "type", width: 120 },
    { title: t("dynamicTable.blockerName"), dataIndex: "name", key: "name" },
    { title: t("dynamicTable.blockerPath"), dataIndex: "path", key: "path" }
  ]);

  const createModalOpen = ref(false);
  const creating = ref(false);
  const createFormRef = ref();
  const createForm = reactive({
    tableKey: "",
    displayName: "",
    description: "",
    template: "basic" as "basic" | "approval" | "dict",
    includeSystemFields: true,
    includeExtraSystemFields: false
  });

  const tableKeyAutoGenerated = ref(false);

  const toSnakeCase = (str: string): string => {
    return str
      .normalize("NFKD")
      .replace(/[\u0300-\u036f]/g, "")
      .replace(/[^\w\s]/g, "")
      .replace(/\s+/g, "_")
      .replace(/[^A-Za-z0-9_]/g, "")
      .toLowerCase()
      .replace(/^[^a-z]+/, "");
  };

  const onDisplayNameChange = () => {
    if (tableKeyAutoGenerated.value || createForm.tableKey === "") {
      const generated = toSnakeCase(createForm.displayName);
      if (generated) {
        createForm.tableKey = generated;
        tableKeyAutoGenerated.value = true;
      }
    }
  };

  const selectedTable = computed(() => {
    if (tableDirectory.value.length === 0) return null;
    return (
      tableDirectory.value.find((item) => item.tableKey === selectedTableKey.value) ??
      tableDirectory.value[0]
    );
  });

  const selectedApprovalBound = computed(() => !!selectedTableDetail.value?.approvalFlowDefinitionId);

  const createFormRules: Record<string, Rule[]> = {
    tableKey: [
      { required: true, message: t("dynamicTable.fieldValueRequired") },
      { pattern: /^[A-Za-z][A-Za-z0-9_]{1,63}$/, message: t("dynamicTable.tableKeyRule") }
    ],
    displayName: [{ required: true, message: t("dynamicTable.fieldValueRequired") }]
  };

  const loadTableDirectory = async () => {
    const currentAppId = appId.value;
    if (!currentAppId) {
      tableDirectory.value = [];
      selectedTableKey.value = "";
      selectedTableDetail.value = null;
      return;
    }
    tableLoading.value = true;
    try {
      const result = await getAppScopedDynamicTables(currentAppId);
      if (!isMounted.value) return;
      tableDirectory.value = result;
      if (result.length === 0) {
        selectedTableKey.value = "";
        selectedTableDetail.value = null;
        return;
      }
      if (!result.some((item) => item.tableKey === selectedTableKey.value)) {
        selectedTableKey.value = result[0].tableKey;
      }
    } catch (error) {
      if (!isMounted.value) return;
      message.error((error as Error).message || t("dynamicTable.loadTablesFailed"));
    } finally {
      if (isMounted.value) tableLoading.value = false;
    }
  };

  const loadSelectedTableDetail = async (tableKeySnapshot: string = selectedTableKey.value) => {
    if (!tableKeySnapshot) {
      selectedTableDetail.value = null;
      return;
    }
    detailLoading.value = true;
    try {
      const detail = await getDynamicTableSummary(tableKeySnapshot, appId.value ?? undefined);
      if (!isMounted.value || selectedTableKey.value !== tableKeySnapshot) return;
      selectedTableDetail.value = detail;
    } catch (error) {
      if (!isMounted.value) return;
      selectedTableDetail.value = null;
      message.error((error as Error).message || t("dynamicTable.loadTableDetailFailed"));
    } finally {
      if (isMounted.value) detailLoading.value = false;
    }
  };

  const refreshAll = async () => {
    const requestId = ++refreshRequestId;
    await loadTableDirectory();
    if (requestId !== refreshRequestId) return;
    const tableKeySnapshot = selectedTableKey.value;
    if (!tableKeySnapshot) {
      selectedTableDetail.value = null;
      return;
    }
    queueMicrotask(() => {
      if (requestId !== refreshRequestId || selectedTableKey.value !== tableKeySnapshot) return;
      void loadSelectedTableDetail(tableKeySnapshot);
    });
  };

  const selectTable = (tableKey: string) => {
    selectedTableKey.value = tableKey;
    void loadSelectedTableDetail();
  };

  const goToDesign = (tableKey: string) => {
    void router.push(`/apps/${appKey.value}/data/${encodeURIComponent(tableKey)}/design`);
  };

  const goToRecords = (tableKey: string) => {
    void router.push(`/apps/${appKey.value}/data/${encodeURIComponent(tableKey)}`);
  };

  const openCreateTableModal = () => {
    createForm.tableKey = "";
    createForm.displayName = "";
    createForm.description = "";
    createForm.template = "basic";
    createForm.includeSystemFields = true;
    createForm.includeExtraSystemFields = false;
    tableKeyAutoGenerated.value = false;
    createModalOpen.value = true;
  };

  const handleCreateTable = async () => {
    const currentAppId = appId.value;
    if (!currentAppId) return;
    try {
      await createFormRef.value?.validate();
    } catch {
      return;
    }
    creating.value = true;
    try {
      const tableKey = createForm.tableKey.trim();
      const fields: DynamicFieldDefinition[] = [
        {
          name: "id",
          displayName: t("dynamicTable.defaultFieldId"),
          fieldType: "Long",
          allowNull: false,
          isPrimaryKey: true,
          isAutoIncrement: true,
          isUnique: true,
          defaultValue: null,
          sortOrder: 1
        }
      ];
      let sortOrder = 2;
      if (createForm.template === "basic" || createForm.template === "approval") {
        fields.push({
          name: "name",
          displayName: t("dynamicTable.defaultFieldName"),
          fieldType: "String",
          length: 128,
          allowNull: false,
          isPrimaryKey: false,
          isAutoIncrement: false,
          isUnique: false,
          defaultValue: "",
          sortOrder: sortOrder++
        });
      }
      if (createForm.template === "dict") {
        fields.push(
          {
            name: "code",
            displayName: t("dynamicTable.defaultFieldCode"),
            fieldType: "String",
            length: 64,
            allowNull: false,
            isPrimaryKey: false,
            isAutoIncrement: false,
            isUnique: true,
            defaultValue: "",
            sortOrder: sortOrder++
          },
          {
            name: "label",
            displayName: t("dynamicTable.defaultFieldLabel"),
            fieldType: "String",
            length: 128,
            allowNull: false,
            isPrimaryKey: false,
            isAutoIncrement: false,
            isUnique: false,
            defaultValue: "",
            sortOrder: sortOrder++
          },
          {
            name: "sort_order",
            displayName: t("dynamicTable.defaultFieldSortOrder"),
            fieldType: "Int",
            allowNull: true,
            isPrimaryKey: false,
            isAutoIncrement: false,
            isUnique: false,
            defaultValue: "0",
            sortOrder: sortOrder++
          }
        );
      }
      if (createForm.includeSystemFields) {
        fields.push(
          {
            name: "created_at",
            displayName: t("dynamicTable.defaultFieldCreatedAt"),
            fieldType: "DateTime",
            allowNull: true,
            isPrimaryKey: false,
            isAutoIncrement: false,
            isUnique: false,
            defaultValue: null,
            sortOrder: sortOrder++
          },
          {
            name: "updated_at",
            displayName: t("dynamicTable.defaultFieldUpdatedAt"),
            fieldType: "DateTime",
            allowNull: true,
            isPrimaryKey: false,
            isAutoIncrement: false,
            isUnique: false,
            defaultValue: null,
            sortOrder: sortOrder++
          }
        );
      }
      if (createForm.includeExtraSystemFields && createForm.includeSystemFields) {
        fields.push(
          {
            name: "created_by",
            displayName: t("dynamicTable.defaultFieldCreatedBy"),
            fieldType: "Long",
            allowNull: true,
            isPrimaryKey: false,
            isAutoIncrement: false,
            isUnique: false,
            defaultValue: null,
            sortOrder: sortOrder++
          },
          {
            name: "updated_by",
            displayName: t("dynamicTable.defaultFieldUpdatedBy"),
            fieldType: "Long",
            allowNull: true,
            isPrimaryKey: false,
            isAutoIncrement: false,
            isUnique: false,
            defaultValue: null,
            sortOrder: sortOrder++
          },
          {
            name: "is_deleted",
            displayName: t("dynamicTable.defaultFieldIsDeleted"),
            fieldType: "Bool",
            allowNull: false,
            isPrimaryKey: false,
            isAutoIncrement: false,
            isUnique: false,
            defaultValue: "false",
            sortOrder: sortOrder++
          }
        );
      }
      await createDynamicTable({
        appId: currentAppId,
        tableKey,
        displayName: createForm.displayName.trim(),
        description: createForm.description.trim() || null,
        dbType: "Sqlite",
        fields,
        indexes: []
      });
      message.success(t("dynamicTable.createTableSuccess"));
      createModalOpen.value = false;
      await loadTableDirectory();
      selectedTableKey.value = tableKey;
      goToDesign(tableKey);
    } catch (error) {
      message.error((error as Error).message || t("dynamicTable.createTableFailed"));
    } finally {
      creating.value = false;
    }
  };

  const handleDeleteTable = async (tableKey: string) => {
    try {
      const check = await getDynamicTableDeleteCheck(tableKey);
      if (!check.canDelete) {
        blockerRows.value = check.blockers;
        deleteWarnings.value = check.warnings;
        blockerModalOpen.value = true;
        message.warning(t("dynamicTable.deleteBlockedTip"));
        return;
      }
      await deleteDynamicTable(tableKey);
      message.success(t("dynamicTable.deleteSuccess"));
      await loadTableDirectory();
      await loadSelectedTableDetail();
    } catch (error) {
      message.error((error as Error).message || t("dynamicTable.deleteFailed"));
    }
  };

  const handleArchiveTable = async (tableKey: string) => {
    try {
      await archiveDynamicTable(tableKey);
      message.success(t("dynamicTable.archiveTableSuccess"));
      await loadTableDirectory();
      await loadSelectedTableDetail();
    } catch (error) {
      message.error((error as Error).message || t("dynamicTable.archiveTableFailed"));
    }
  };

  const handleRestoreTable = async (tableKey: string) => {
    try {
      await restoreDynamicTable(tableKey);
      message.success(t("dynamicTable.restoreTableSuccess"));
      await loadTableDirectory();
      await loadSelectedTableDetail();
    } catch (error) {
      message.error((error as Error).message || t("dynamicTable.restoreTableFailed"));
    }
  };

  onMounted(() => {
    void refreshAll();
  });

  watch(appId, (next, previous) => {
    if (next === previous) return;
    selectedTableKey.value = "";
    selectedTableDetail.value = null;
    void refreshAll();
  });

  watch(selectedTableKey, (next) => {
    if (next) void loadSelectedTableDetail(next);
  });

  return {
    t,
    tableLoading,
    detailLoading,
    sidebarKeyword,
    selectedTableKey,
    tableDirectory,
    selectedTableDetail,
    blockerModalOpen,
    blockerRows,
    deleteWarnings,
    statusLabel,
    statusTagColor,
    filteredTables,
    fieldColumns,
    blockerColumns,
    createModalOpen,
    creating,
    createFormRef,
    createForm,
    onDisplayNameChange,
    selectedTable,
    selectedApprovalBound,
    createFormRules,
    refreshAll,
    selectTable,
    goToDesign,
    goToRecords,
    openCreateTableModal,
    handleCreateTable,
    handleDeleteTable,
    handleArchiveTable,
    handleRestoreTable
  };
}
