//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: Microsoft.Extensions.Configuration.UserSecrets.UserSecretsIdAttribute("1e21b31f-1fa1-4576-9642-d9ea2f069279")]
[assembly: System.Reflection.AssemblyCompanyAttribute("Atlas.WebApi")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+29dbbb9e164778941f0e8ec6970a6fc3b4ee59ab")]
[assembly: System.Reflection.AssemblyProductAttribute("Atlas.WebApi")]
[assembly: System.Reflection.AssemblyTitleAttribute("Atlas.WebApi")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]

// Generated by the MSBuild WriteCodeFragment class.

