import { describe, expect, it } from "vitest";
import type { MicroflowActionActivity, MicroflowMetadataCatalog } from "../../schema";
import { deriveAutoGeneratedCaption, syncActionActivityCaption } from "./auto-generated-caption";

const metadataCatalog = {
  entities: [
    { qualifiedName: "Sales.Order", name: "Order", moduleName: "Sales", attributes: [], associations: [] },
  ],
  enumerations: [],
  microflows: [],
} as unknown as MicroflowMetadataCatalog;

describe("auto-generated-caption", () => {
  it("derives entity-based captions for create object", () => {
    const activity = actionActivity({
      kind: "createObject",
      officialType: "Microflows$CreateObjectAction",
      entityQualifiedName: "Sales.Order",
      outputVariableName: "Order",
      memberChanges: [],
      commit: { enabled: false, withEvents: true, refreshInClient: false },
    });

    expect(deriveAutoGeneratedCaption(activity.action, metadataCatalog)).toBe("Create Order");
  });

  it("derives target-based captions for call microflow", () => {
    const activity = actionActivity({
      kind: "callMicroflow",
      officialType: "Microflows$MicroflowCallAction",
      targetMicroflowId: "mf-1",
      targetMicroflowDisplayName: "ACT_ProcessOrder",
      parameterMappings: [],
      returnValue: { storeResult: false },
      callMode: "sync",
    });

    expect(deriveAutoGeneratedCaption(activity.action, metadataCatalog)).toBe("Call ACT_ProcessOrder");
  });

  it("derives request-based captions for REST calls", () => {
    const activity = actionActivity({
      kind: "restCall",
      officialType: "Microflows$RestCallAction",
      request: {
        method: "GET",
        urlExpression: { raw: "https://api.example.com/orders?status=New", referencedVariables: [], diagnostics: [] },
        headers: [],
        queryParameters: [],
        body: { kind: "none" },
      },
      response: { handling: { kind: "ignore" } },
      timeoutSeconds: 30,
    });

    expect(deriveAutoGeneratedCaption(activity.action, metadataCatalog)).toBe("GET /orders?status=New");
  });

  it("keeps object and action captions aligned when auto-generate is enabled", () => {
    const next = syncActionActivityCaption(actionActivity({
      kind: "createVariable",
      officialType: "Microflows$CreateVariableAction",
      variableName: "Discount",
      dataType: { kind: "decimal" },
      initialValue: { raw: "0.15", referencedVariables: [], diagnostics: [] },
      readonly: false,
    }, { autoGenerateCaption: true, caption: "stale", actionCaption: "old" }), metadataCatalog);

    expect(next.caption).toBe("Create Discount");
    expect(next.action.caption).toBe("Create Discount");
  });
});

function actionActivity(actionPatch: Record<string, unknown>, options?: { autoGenerateCaption?: boolean; caption?: string; actionCaption?: string }): MicroflowActionActivity {
  const kind = String(actionPatch.kind ?? "createVariable");
  const caption = options?.caption ?? "Action";
  return {
    id: `${kind}-activity`,
    stableId: `${kind}-activity`,
    kind: "actionActivity",
    officialType: "Microflows$ActionActivity",
    caption,
    documentation: "",
    relativeMiddlePoint: { x: 0, y: 0 },
    size: { width: 160, height: 80 },
    ports: [],
    autoGenerateCaption: options?.autoGenerateCaption ?? false,
    backgroundColor: "default",
    editor: {},
    action: {
      id: `${kind}-action`,
      kind,
      officialType: String(actionPatch.officialType ?? "Microflows$Action"),
      caption: options?.actionCaption ?? caption,
      documentation: "",
      errorHandlingType: "rollback",
      editor: { category: "call", iconKey: kind, availability: "supported" },
      ...actionPatch,
    } as never,
  } as unknown as MicroflowActionActivity;
}
