@baseUrl = http://localhost:5000
@tenantId = 00000000-0000-0000-0000-000000000001
@username = admin
@password = P@ssw0rd!

### 登录
# @name login
POST {{baseUrl}}/api/v1/auth/token
Content-Type: application/json
X-Tenant-Id: {{tenantId}}

{
  "username": "{{username}}",
  "password": "{{password}}"
}

###
@accessToken = {{login.response.body.$.data.accessToken}}

### 查询 SQLite 字段类型
GET {{baseUrl}}/api/v1/dynamic/meta/field-types?dbType=sqlite
Authorization: Bearer {{accessToken}}
X-Tenant-Id: {{tenantId}}

### 查询 MySql 字段类型
GET {{baseUrl}}/api/v1/dynamic/meta/field-types?dbType=mysql
Authorization: Bearer {{accessToken}}
X-Tenant-Id: {{tenantId}}
