@baseUrl = http://localhost:5000
@tenantId = 00000000-0000-0000-0000-000000000001
@username = admin
@password = P@ssw0rd!

### Login to get token (Execute this first)
# @name login
POST {{baseUrl}}/auth/token
Content-Type: application/json
X-Tenant-Id: {{tenantId}}

{
  "username": "{{username}}",
  "password": "{{password}}"
}

###
@accessToken = {{login.response.body.$.data.accessToken}}

### Get Menus (Paged)
GET {{baseUrl}}/menus?pageIndex=1&pageSize=10
Authorization: Bearer {{accessToken}}
X-Tenant-Id: {{tenantId}}

### Get Menus (All)
GET {{baseUrl}}/menus/all
Authorization: Bearer {{accessToken}}
X-Tenant-Id: {{tenantId}}

### Create Menu
POST {{baseUrl}}/menus
Content-Type: application/json
Authorization: Bearer {{accessToken}}
X-Tenant-Id: {{tenantId}}

{
  "name": "System",
  "path": "/system",
  "parentId": null,
  "sortOrder": 0,
  "component": "Layout",
  "icon": "settings",
  "permissionCode": "system:admin",
  "isHidden": false
}

### Update Menu
PUT {{baseUrl}}/menus/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}
X-Tenant-Id: {{tenantId}}

{
  "name": "System",
  "path": "/system",
  "parentId": null,
  "sortOrder": 0,
  "component": "Layout",
  "icon": "settings",
  "permissionCode": "system:admin",
  "isHidden": false
}