using System.Text.Json;
using Atlas.Domain.AiPlatform.Enums;

namespace Atlas.Infrastructure.Services.WorkflowEngine.NodeExecutors;

/// <summary>
/// 代码执行节点：当前版本支持简单表达式求值（字符串拼接、变量替换）。
/// 安全沙箱执行（Roslyn Scripting）将在后续版本中实现。
/// Config 参数：code、language（默认 "expression"）、outputKey
/// </summary>
public sealed class CodeRunnerNodeExecutor : INodeExecutor
{
    public WorkflowNodeType NodeType => WorkflowNodeType.CodeRunner;

    public Task<NodeExecutionResult> ExecuteAsync(NodeExecutionContext context, CancellationToken cancellationToken)
    {
        var outputs = new Dictionary<string, JsonElement>(StringComparer.OrdinalIgnoreCase);

        string code = "";
        string language = "javascript";
        JsonElement? inputParamsArray = null;

        if (context.Node.Config.TryGetValue("inputs", out var inputsRaw) && inputsRaw.ValueKind == JsonValueKind.Object)
        {
            if (inputsRaw.TryGetProperty("code", out var codeProp))
                code = codeProp.GetString() ?? "";
            
            if (inputsRaw.TryGetProperty("language", out var langProp))
                language = langProp.ValueKind == JsonValueKind.Number ? langProp.GetInt32().ToString() : (langProp.GetString() ?? "javascript");
            
            if (inputsRaw.TryGetProperty("inputParameters", out var ip))
                inputParamsArray = ip;
        }
        else
        {
            code = context.GetConfigString("code");
            language = context.GetConfigString("language", "javascript");
        }

        if (string.IsNullOrWhiteSpace(code))
        {
            return Task.FromResult(new NodeExecutionResult(true, outputs));
        }

        var paramDict = new Dictionary<string, JsonElement>();
        if (inputParamsArray?.ValueKind == JsonValueKind.Array)
        {
            foreach (var ip in inputParamsArray.Value.EnumerateArray())
            {
                if (ip.TryGetProperty("name", out var n) && n.ValueKind == JsonValueKind.String)
                {
                    var name = n.GetString() ?? "";
                    if (context.Variables.TryGetValue(name, out var val))
                    {
                        paramDict[name] = val;
                    }
                }
            }
        }
        else
        {
            foreach (var kvp in context.Variables)
            {
                if (!kvp.Key.Contains('.')) // Only pass root variables
                {
                    paramDict[kvp.Key] = kvp.Value;
                }
            }
        }

        try
        {
            // Jint doesn't support TypeScript syntax or top-level async functions easily without Babel.
            // We strip out the basic TypeScript annotations generated by the UI template.
            string cleanCode = code;
            cleanCode = System.Text.RegularExpressions.Regex.Replace(cleanCode, @"\:\s*Args", "");
            cleanCode = System.Text.RegularExpressions.Regex.Replace(cleanCode, @"\:\s*Promise\<[^>]+\>", "");
            cleanCode = System.Text.RegularExpressions.Regex.Replace(cleanCode, @"\:\s*Output", "");
            cleanCode = cleanCode.Replace("async function", "function");
            cleanCode = cleanCode.Replace("await ", "");

            var engine = new Jint.Engine();

            var rawArgs = JsonSerializer.Serialize(paramDict);
            engine.SetValue("rawArgs", rawArgs);
            engine.Execute("var args = { params: JSON.parse(rawArgs) };");
            
            // Execute the script to define the main function
            engine.Execute(cleanCode);

            // Call main({ params: ... })
            var result = engine.Evaluate("main(args)");
            
            if (result != null)
            {
                var obj = result.ToObject();
                if (obj is IDictionary<string, object> dict)
                {
                    foreach (var kvp in dict)
                    {
                        outputs[kvp.Key] = JsonSerializer.SerializeToElement(kvp.Value);
                    }
                }
                else
                {
                    outputs["code_output"] = JsonSerializer.SerializeToElement(obj);
                }
            }

            return Task.FromResult(new NodeExecutionResult(true, outputs));
        }
        catch (Exception ex)
        {
            return Task.FromResult(new NodeExecutionResult(false, outputs, $"代码执行失败: {ex.Message}"));
        }
    }
}
